config/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from core.views import StartView
from core.views import DateSetView
from account.views import AccountView
from community.views import CommunityView
from player.views import PlayerDetails, PlayerCreate
from team.views import TeamList, TeamDetails, TeamCreate, TeamListRealtime
from match.views import MatchList, MatchDetails, MatchCreate
from balancer.views import MatchmakerView
from account.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', SignUpView.as_view(
        template_name='account/signup.html',), name='signup'),
    path('account/', AccountView.as_view(), name='account'),
    path('login/', LoginView.as_view(
        template_name='account/login.html',), name='login'),

    path('logout/', LogoutView.as_view(
        template_name='account/logout.html',), name='logout'),

    path('community/', CommunityView.as_view(), name='community'),

    path('', StartView.as_view(), name="home"),
    path('set/date/', DateSetView.as_view(), name="set-date"),
    path('balancer/', MatchmakerView.as_view(), name="balancer"),

    # path('player/', PlayerList.as_view(), name='player-list'),
    path('player/<pk>/', PlayerDetails.as_view(), name="player-details"),
    path('new/player/', PlayerCreate.as_view(), name="player-new"),

    path('team/', TeamList.as_view(), name="team-list"),
    path('ladder/', TeamList.as_view(), name="ladder"),
    path('team/<pk>/', TeamDetails.as_view(), name="team-details"),
    path('new/team/', TeamCreate.as_view(), name="team-new"),
    path('realtime/team/', TeamListRealtime.as_view(), name="team-realtime"),

    path('match/', MatchList.as_view(), name="match-list"),
    path('match/<pk>/', MatchDetails.as_view(), name="match-details"),
    path('tracker/', MatchCreate.as_view(), name="match-new"),
]

match/models.py
""" Match model """
from copy import deepcopy
from datetime import datetime, timedelta, date
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class TeamMatchBase():  # pylint: disable=too-few-public-methods
    """ Class to deduplicate team and match model"""
    frm = datetime(2000, 1, 1).date()
    to_ = datetime(3000, 1, 1).date()

    @classmethod
    def set_from_to(cls, frm, to_):
        """ sets new date filter """
        def to_date(date_x):
            """ date_x may be date, datetime or string object
            returns date object
            """
            return {
                datetime: lambda: date_x.date,
                date: lambda: date_x,
                str: lambda: datetime.strptime(date_x, '%Y-%m-%d').date(),
            }.get(type(date_x))()

        cls.frm = to_date(frm)
        cls.to_ = to_date(to_) + timedelta(days=1)


class Match(TeamMatchBase, models.Model):
    """ Match model
    workaround: frm and to_ are the last setted datefilters
    I dont want to have requests inside the model
    """
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    firstteam = models.ForeignKey(
        'team.Team',
        related_name='Team1',
        on_delete=models.CASCADE,
        default=None,
        verbose_name="Team 1",
    )

    secondteam = models.ForeignKey(
        'team.Team',
        related_name='Team2',
        on_delete=models.CASCADE,
        default=None,
        verbose_name="Team 2",
    )

    firstteam_goals = models.PositiveSmallIntegerField(
        verbose_name="T1 goals",
        default=0
    )

    secondteam_goals = models.PositiveSmallIntegerField(
        verbose_name="T2 goals",
        default=0
    )

    date_time = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        verbose_name="Finish-Date",
    )

    @property
    def goal_difference(self):
        """ positiv=win_firstteam, negativ=win_secondteam """
        return self.firstteam_goals - self.secondteam_goals

    @property
    def rematches(self):
        """ returns list of matches with same teams """
        ret = self.previous_matches(self.firstteam, self.secondteam)
        return [x for x in sorted(ret, key=lambda x: x.pk)
                if x.pk is not self.pk]

    @property
    def rematches_erlier_later(self):
        """ returns rematches (earlier, later) """
        earlier, later = [], []
        for match in self.rematches:
            if match.date_time < self.date_time:
                earlier.append(match)
            else:
                later.append(match)
        return earlier, later

    @classmethod
    def previous_matches(cls, firstteam, secondteam):
        """ calculates previous matches by firstteam, secondteam """
        ret = []
        ret += cls.objects.filter(firstteam=firstteam, secondteam=secondteam,
                                  date_time__range=(cls.frm, cls.to_))
        ret += cls.objects.filter(firstteam=secondteam, secondteam=firstteam,
                                  date_time__range=(cls.frm, cls.to_))
        return sorted(ret, key=lambda x: x.pk)

    def new_result(self):
        """ sets new result to players """
        for player in self.firstteam.players.all():
            player.new_result(
                self.firstteam_goals - self.secondteam_goals,
                self.secondteam
            )

        for player in self.secondteam.players.all():
            player.new_result(
                self.secondteam_goals - self.firstteam_goals,
                self.secondteam
            )

    def pov(self, pov_team):
        """ changes the point of view """
        self_copy = deepcopy(self)
        if self.firstteam != pov_team:
            self_copy.firstteam, self_copy.secondteam = \
                self_copy.secondteam, self_copy.firstteam

            self_copy.firstteam_goals, self_copy.secondteam_goals = \
                self_copy.secondteam_goals, self_copy.firstteam_goals
        return self_copy

    def save(self, *args, **kwargs):  # pylint: disable=W0221
        if self.firstteam.pk is self.secondteam.pk:
            raise ValidationError(
                "%s can't play against itself" % (
                    str(self.firstteam.pk) + "",
                ),
                params={'value': self.firstteam.pk},
            )
        self.new_result()
        super().save(*args, **kwargs)

    def __eq__(self, other):
        return self.pk == other.pk

    def __lt__(self, other):
        return self.pk < other.pk

    def __str__(self):
        return str("ID%s: %s vs. %s (%s:%s)" % (
            self.id,
            self.firstteam.get_team_name_or_members(),
            self.secondteam.get_team_name_or_members(),
            self.firstteam_goals,
            self.secondteam_goals,
        ))

    class Meta:
        verbose_name_plural = "Matches"

match/forms.py
""" match forms """
from django import forms

from team.models import Team
from player.models import Player
from .models import Match


class MatchCreateForm(forms.ModelForm):
    """ match creation form """

    def __init__(self, *args, **kwargs):
        #owner = kwargs.pop('owner')
        super().__init__(*args, **kwargs)
        self.fields['firstteam'].queryset = Team.objects.filter() #owner=owner
        self.fields['secondteam'].queryset = Team.objects.filter()#owner=owner

    class Meta:
        model = Match
        fields = [
            'firstteam',
            'secondteam',
            'firstteam_goals',
            'secondteam_goals',
        ]

match/views.py
""" views of match module """
from datetime import datetime, timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView

from .models import Match
from .forms import MatchCreateForm


class MatchList(LoginRequiredMixin, ListView):\
        # pylint: disable=too-many-ancestors
    """ View List of matches """
    model = Match

    def get_queryset(self):
        if 'from' in self.request.session:
            frm = self.request.session['from']
        else:
            frm = '2000-01-01'

        if 'to' in self.request.session:
            to_ = datetime.strptime(
                self.request.session['to'], '%Y-%m-%d').date()
            to_ += timedelta(days=1)
            to_ = to_.strftime('%Y-%m-%d')
        else:
            to_ = '3000-01-01'
        return Match.objects.filter(
            date_time__range=[frm, to_],
            #owner=self.request.user
        )


class MatchDetails(LoginRequiredMixin, DetailView):\
        # pylint: disable=too-many-ancestors
    """ View Details of a single view """
    model = Match

    def get_queryset(self):
        Match.set_from_to(
            self.request.session['from'], self.request.session['to'])
        return Match.objects.filter() #owner=self.request.user)


class MatchCreate(LoginRequiredMixin, CreateView):\
        # pylint: disable=too-many-ancestors
    """ create new match-form"""
    model = Match
    form_class = MatchCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        #kwargs['owner'] = self.request.user
        return kwargs

    def get_initial(self):
        self.success_url = self.request.path
        initial = super().get_initial()
        initial = initial.copy()

        initial['firstteam'] = self.request.session['last_firstteam'] \
            if 'last_firstteam' in self.request.session \
            else ''

        initial['secondteam'] = self.request.session['last_secondteam'] \
            if 'last_secondteam' in self.request.session \
            else ''

        if 'firstteam' in self.request.GET:
            initial['firstteam'] = int(self.request.GET['firstteam'])
        if 'secondteam' in self.request.GET:
            initial['secondteam'] = int(self.request.GET['secondteam'])
        return initial

    def form_valid(self, form):
        #=======================================================================
        # owner = self.request.user
        # form.instance.owner = owner
        #=======================================================================
        valid = False
        if form.cleaned_data['firstteam_goals'] \
                == 0 and form.cleaned_data['secondteam_goals'] == 0:
            form.errors['error'] = 'Score cannot be 0:0'
        elif form.cleaned_data['firstteam'] == form.cleaned_data['secondteam']:
            form.errors['error'] = 'Choose different teams!'
        else:
            self.request.session['last_firstteam'] = \
                int(self.request.POST['firstteam'])
            self.request.session['last_secondteam'] = \
                int(self.request.POST['secondteam'])
            valid = True

        return super().form_valid(form) if valid else \
            super().form_invalid(form)

templates/match/match_detail.html
{% load elements %}
<div class=" container-fluid">
	<div class="row">
		<table class="table table-sm text-center">
			<tr>
				<th>Rematches:</th>
			<tr>
				<td>
					{% with rematches=match.rematches %}
						{% if rematches %}
							{% for rematch in match.rematches %}
								{% match_badge rematch pov_team=match.firstteam t2show=False %}
							{% endfor %}
						{% endif %}
					{% endwith %}
				</td>
			<tr>
		</table>
	</div>
</div>

templates/match/match_form.html
{% extends 'base.html' %}
{% block title %}Tracker{% endblock %}
{% block description %}Track your matches and view the ranking ladder with realtime results. Forget your manual counter. This is also working with tablets and mobiles very well.{% endblock %}
{% block keywords %}counter, track, match, realtime, switch, ladder, ranking{% endblock %}

{% block tipps %}
	<div class="alert alert-success" role="alert">
		Don't forget to save when the game is finished.
	</div>
	<hr />
{% endblock %}
{% block var_link %}{% endblock %}

{% block head %}
<style>

</style>
<script>
	loadLadderRealtime();
</script>
{% endblock %}

{% block content %}
{% load humanize %}
<div class="container bg">
<form id="new-match-form" method="post">{% csrf_token %}
	{% if form.fields.firstteam.choices|length > 2 %}
		{% if form.errors %}
				<div class="alert alert-danger" role="alert">
					{{ form.errors.error }}
			</div>
		{% endif %}
	{% else %}
		<div class="alert alert-danger" role="alert">
			A Match needs at least 2 teams/player-teams. <a href="{% url 'player-new' %}" class="btn btn-warning">Create them first</a>
		</div>
	{% endif %}
<table id="match-form" class="table table-sm table-bordered table-hover">
	<tr>
		<td>{{ form.firstteam }}</td>
		<td title="switch teams" class="middle" colspan=2>
			<strong>vs.</strong><br /><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M6.99 11L3 15l3.99 4v-3H14v-2H6.99v-3zM21 9l-3.99-4v3H10v2h7.01v3L21 9z"/><path d="M0 0h24v24H0z" fill="none"/></svg>
		</td>
		<td>{{ form.secondteam }}</td>
	</tr>
	<tr>
		<td id="firstteam-controls" colspan=2>
			<input class="plus btn btn-success" type="button" value="+" onclick="increment($('#id_firstteam_goals'))" />
			{{ form.firstteam_goals }}
			<input class="minus btn btn-danger" type="button" value="-" onclick="decrement($('#id_firstteam_goals'))" />
		</td>
		<td id="secondteam-controls" colspan=2>
			<input class="plus btn btn-success" type="button" value="+" onclick="increment($('#id_secondteam_goals'))" />
			{{ form.secondteam_goals }}
			<input class="minus btn btn-danger" type="button" value="-" onclick="decrement($('#id_secondteam_goals'))" />
		</td>
	</tr>
</table>
<input class="btn btn-primary btn btn-block" type="submit" value="Game finished (save)" />
</form>
</div>
<div class="container-fluid">
	<div id="match-realtime" class="row" style="margin-top:40px"></div>
</div>
{% endblock %} 

templates/match/match_list.html
{% extends 'base.html' %}
{% block title %}Matches{% endblock %}
{% block description %}This is the overview on all matches and their rematches within the filtered time. The Timeline shows you which matches where before and after this match.{% endblock %}
{% block keywords %}timeline, previous, matches, rematches, same, teams, before, after{% endblock %}

{% block tipps %}
	<div class="alert alert-success" role="alert">
		The timeline views the Matches with same teams in chronological order.
	</div>
	<hr />
{% endblock %}

{% block head %}
<script>
$(document).ready(function() {
	loadDataTables(1, 'asc');
});
</script>
{% endblock %}


{% block content %}
{% load humanize elements %}
<div class="table-responsive bg">
<table class="datatable table table-striped table-bordered table-hover" >
	<thead>
		<tr>
			<th>ID</th>
			<th>Time</th>
			<th>First team (and <span class="badge badge-light">Players</span>)</th>
			<th>Second team (and <span class="badge badge-light">Players</span>)</th>
			<th>Result</th>
			<th>Rematches (Timeline)</th>
		</tr>
	</thead>
{% for match in object_list %}
	<tr>
		<th><a href="{% url 'match-details' match.pk %}">{{ match.pk }}</a></th>
		<td data-order="{{match.pk}}" title="{{match.date_time|naturaltime}}">{{ match.date_time }}</td>
		<td title="{{match.firstteam.verbose_name}}">
			{% team_details_badge match.firstteam linkclass='primary'%}
			{% for player in match.firstteam.players.all %}
				{% player_details_badge player %}
			{% endfor %}
		</td>
		<td title="{{match.secondteam.verbose_name}}">
			{% team_details_badge match.secondteam linkclass='secondary'%}
			{% for player in match.secondteam.players.all %}
				{% player_details_badge player %}
			{% endfor %}
		</td>
		<td data-order="{{ match.goal_difference}}">{% match_details_badge match t2show=False%}</td>
		<td data-order="{{match.rematches | length}}">
		{% if match.rematches %}
			<div class="container-fluid" >
				<div class="row">
					{% for rematch in match.rematches_erlier_later.0 %}
						{% match_details_badge rematch match.firstteam t2show=False %}
					{% endfor %}
					<span class="badge badge-success">this</span>
					{% for rematch in match.rematches_erlier_later.1 %}
						{% match_details_badge rematch match.firstteam t2show=False %}
					{% endfor %}
					</ul>
				</div>
			</div>
		{% endif %}
	</td>
{% empty %}
    <li>No player yet.</li>
{% endfor %}
</table>
</div>
{% endblock %}