config/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from core.views import StartView
from core.views import DateSetView
from account.views import AccountView
from community.views import CommunityView
from player.views import PlayerDetails, PlayerCreate
from team.views import TeamList, TeamDetails, TeamCreate, TeamListRealtime
from match.views import MatchList, MatchDetails, MatchCreate
from balancer.views import MatchmakerView
from account.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', SignUpView.as_view(
        template_name='account/signup.html',), name='signup'),
    path('account/', AccountView.as_view(), name='account'),
    path('login/', LoginView.as_view(
        template_name='account/login.html',), name='login'),

    path('logout/', LogoutView.as_view(
        template_name='account/logout.html',), name='logout'),

    path('community/', CommunityView.as_view(), name='community'),

    path('', StartView.as_view(), name="home"),
    path('set/date/', DateSetView.as_view(), name="set-date"),
    path('balancer/', MatchmakerView.as_view(), name="balancer"),

    # path('player/', PlayerList.as_view(), name='player-list'),
    path('player/<pk>/', PlayerDetails.as_view(), name="player-details"),
    path('new/player/', PlayerCreate.as_view(), name="player-new"),

    path('team/', TeamList.as_view(), name="team-list"),
    path('ladder/', TeamList.as_view(), name="ladder"),
    path('team/<pk>/', TeamDetails.as_view(), name="team-details"),
    path('new/team/', TeamCreate.as_view(), name="team-new"),
    path('realtime/team/', TeamListRealtime.as_view(), name="team-realtime"),

    path('match/', MatchList.as_view(), name="match-list"),
    path('match/<pk>/', MatchDetails.as_view(), name="match-details"),
    path('tracker/', MatchCreate.as_view(), name="match-new"),
]

team/models.py
""" model for team objects """
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum, Q

from match.models import Match, TeamMatchBase


class Team(TeamMatchBase, models.Model):  # pylint: disable=too-many-public-methods
    # :TODO: Rebuild with Team as subclass
    """ Teams are Season-based
    -> every season there are new values
    -> values are calculated from the matches
    workaround: frm and to_ are the last setted datefilters
    I dont want to have requests inside the model
    """

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    teamname = models.CharField(
        max_length=50, verbose_name="Teamname",
        blank=True,
    )
    players = models.ManyToManyField('player.Player')

    @property
    def is_player_team(self):
        """ True if only one player in team """
        return len(self.players.all()) == 1

    @property
    def name(self):
        """ returns only the name of team """
        name = self.teamname
        return name if name else False

    @property
    def team_score(self):
        """ calculate based on matches """
        results = self.get_win_draw_lose
        return len(results[0]) * 2 + len(results[1]) * 1

    @property
    def team_rating(self):
        """ Calculates the team strength out of the Player Elo """
        return 0.0 if not self.players.all() else sum(
            [x.player_rating() for x in self.players.all()]
        ) / len(self.players.all())

    @property
    def verbose_name(self):
        """ returns more verbose name with members and ratings """
        return str("%s (TeamScore: %s; TeamRating: %s Members: %s)" % (
            self.get_team_name_or_members(),
            int(self.team_score + 0.5),
            int(self.team_rating + 0.5),
            ", ".join([x.nick for x in self.players.all()])
        ))

    @property
    def team_rating_as_int(self):
        """ returns team rating as integer """
        return int(self.team_rating + 0.5)

    def get_team_name_or_members(self):
        """ returns teamname if existing else teamplayers """
        return self.teamname if self.teamname else '[%s]' % (
            ', '.join([x.nick for x in self.players.all()]))

    @property
    def has_game(self):
        """ true if team has already a game """
        win, draw, lose = self.get_win_draw_lose
        return win or draw or lose  # :TODO:

    @property
    def win_lose_factor(self):
        """ Returns the value of wins-loses """
        return len(self.get_win_draw_lose[0]) - len(self.get_win_draw_lose[1])

    @property
    def get_win_draw_lose(self):
        """ returns ([win-games], [draw-games], [lose-games]) """
        win, draw, lose = [], [], []
        matches = Match.objects.filter(
            firstteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        )
        for match in matches:
            result = match.firstteam_goals - match.secondteam_goals
            if result > 0:
                win.append(match)
            elif result == 0:
                draw.append(match)
            elif result < 0:
                lose.append(match)

        matches = Match.objects.filter(
            secondteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        )
        for match in matches:
            result = match.secondteam_goals - match.firstteam_goals
            if result > 0:
                win.append(match)
            elif result == 0:
                draw.append(match)
            elif result < 0:
                lose.append(match)
        return win, draw, lose

    @property
    def matches_chronologic(self):
        """ returns the matches of the team cronological ordered """
        return sorted(
            Match.objects.filter(
                Q(firstteam_id=self.pk) | Q(secondteam_id=self.pk
                                            ), date_time__range=(
                                                self.frm, self.to_
                                                )), key=id)

    @property
    def get_win_draw_lose_sum(self):
        """ returns win, draw, lost games """
        win, draw, lose = self.get_win_draw_lose
        return len(win) + len(draw) + len(lose)

    @property
    def get_win_draw_lose_percent(self):
        """ percentage of w,d,l """
        win, draw, lose = self.get_win_draw_lose
        sum_ = len(win) + len(draw) + len(lose)
        sum_ = 100 / sum_ if sum_ else 0
        return len(win) * sum_, len(draw) * sum_, len(lose) * sum_

    @property
    def close_win_lose(self):
        """ returns ([closewin-games], [loselose-games]) """
        close_win, close_lose = [], []
        for match in Match.objects.filter(
                firstteam=self, date_time__range=(self.frm, self.to_)):
            if match.goal_difference == 1:
                close_win.append(match)
            elif match.goal_difference == -1:
                close_lose.append(match)

        for match in Match.objects.filter(
                secondteam=self, date_time__range=(self.frm, self.to_)):
            if match.goal_difference == 1:
                close_lose.append(match)
            elif match.goal_difference == -1:
                close_win.append(match)

        return (close_win, close_lose)

    @property
    def close_win_lose_percent(self):
        """ calculates the lose won and lost games """
        win, lose = self.close_win_lose
        sum_ = len(win) + len(lose)
        sum_ = 100 / sum_ if sum_ else 0
        return len(win) * sum_, len(lose) * sum_

    @property
    def close_wl_factor(self):
        """ closewin - closelose """
        return len(self.close_win_lose[0]) - len(self.close_win_lose[1])

    @property
    def goal_own_foreign(self):
        """ returns (ongoals, foreigngoals) """
        own, foreign = 0, 0
        sum_ = Match.objects.filter(
            firstteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        ).aggregate(Sum('firstteam_goals'))['firstteam_goals__sum']
        own += sum_ if sum_ else 0

        sum_ = Match.objects.filter(
            secondteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        ).aggregate(Sum('secondteam_goals'))['secondteam_goals__sum']
        own += sum_ if sum_ else 0

        sum_ = Match.objects.filter(
            firstteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        ).aggregate(Sum('secondteam_goals'))['secondteam_goals__sum']
        foreign += sum_ if sum_ else 0

        sum_ = Match.objects.filter(
            secondteam_id=self.pk,
            date_time__range=(self.frm, self.to_)
        ).aggregate(Sum('firstteam_goals'))['firstteam_goals__sum']

        foreign += sum_ if sum_ else 0
        return own, foreign

    @property
    def goal_own_foreign_percent(self):
        """ goal percentage """
        own, foreign = self.goal_own_foreign
        sum_ = own + foreign
        sum_ = 100 / sum_ if sum_ else 0
        return own * sum_, foreign * sum_

    @property
    def goal_factor(self):
        """ owngoals - foreigngoals """
        if self.goal_own_foreign[0] == 0 and self.goal_own_foreign[1] == 0:
            return -1000
        return self.goal_own_foreign[0] - self.goal_own_foreign[1]

    @classmethod
    def players_have_team(cls, player_obj_lst):
        """ returns [teams of player_obj_lst] should ever be one team """
        for team in cls.objects.all():
            if sorted(player_obj_lst, key=lambda x: x.pk) \
                    == sorted(team.players.all(), key=lambda x: x.pk):
                return team
        return None

    def __str__(self):
        return '%s (%s)' % (
            self.get_team_name_or_members(),
            self.team_rating_as_int
        )

balancer/forms.py
""" forms for balancer views """
from django import forms

from player.models import Player


class BalancerForm(forms.Form):
    """ form for balancer """

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        choices = sorted(Player.objects.filter())
        c = ((x.pk, x) for x in choices)
        choices = tuple(c)
        self.fields['players'] = forms.MultipleChoiceField(
            choices=choices,
            widget=forms.CheckboxSelectMultiple,
        )
        self.fields['count'] = forms.ChoiceField(
            label="Constellation",
            choices=[
                [2, '1 vs 1'],
                [3, '2 vs 1'],
                [4, '2 vs 2'],
                [5, '3 vs 2'],
                [6, '3 vs 3'],
            ],
            widget=forms.RadioSelect(attrs={}),
        )

matchmaker/forms.py
""" forms for matchmaker views """
from django import forms

from player.models import Player


class MatchmakerForm(forms.Form):
    """ form for matchmaker """

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        choices = sorted(Player.objects.filter(owner=request.user))
        choices = ((x.pk, x) for x in choices)
        choices = tuple(choices)
        self.fields['players'] = forms.MultipleChoiceField(
            choices=choices,
            widget=forms.CheckboxSelectMultiple,
        )
        self.fields['count'] = forms.ChoiceField(
            label="Constellation",
            choices=[
                [2, '1 vs 1'],
                [3, '2 vs 1'],
                [4, '2 vs 2'],
                [5, '3 vs 2'],
                [6, '3 vs 3'],
            ],
            widget=forms.RadioSelect(attrs={}),
        )

balancer/views.py
""" views for balancer module """
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from player.models import Player
from team.forms import TeamCreateForm
from match.models import Match
from balancer.forms import BalancerForm
from balancer.models import ConstellationFactory


class MatchmakerView(LoginRequiredMixin, View):
    """ balancer himself """

    def get(self, request):
        """ get method of balancer """
        Match.set_from_to(
            self.request.session['from'], self.request.session['to'])
        context = {}

        if 'players' in request.GET:
            request.session['last_players'] = request.GET.getlist('players')
        if 'count' in request.GET:
            request.session['last_count'] = request.GET.get('count')

        initial_count = int(request.session['last_count']) \
            if 'last_count' in request.session \
            and request.session['last_count'] \
            else 2
        initial_players = request.session['last_players'] \
            if 'last_players' in request.session \
            and request.session['last_players'] \
            else ''

        form = BalancerForm(request, initial={
            'count': initial_count,
            'players': initial_players,
        })

        if 'players' and 'count' in request.GET:
            players = [Player.objects.get(pk=x, owner=request.user)
                       for x in request.GET.getlist('players')]
            context['constellations'] = ConstellationFactory(
                players, int(request.GET.get('count'))
            ).get_constellations()
            if len(request.GET.getlist('players')) \
                    < int(request.GET.get('count')):
                form.errors['error'] = 'Choose more players !'
        context["matchmaker_form"] = form
        return render(
            request,
            template_name="balancer/matchmaker_form.html",
            context=context,
        )

matchmaker/views.py
""" views for matchmaker module """
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from player.models import Player
from match.models import Match
from .forms import MatchmakerForm
from .models import ConstellationFactory


class MatchmakerView(LoginRequiredMixin, View):
    """ matchmaker himself """

    def get(self, request):
        """ get method of matchmaker """
        Match.set_from_to(
            self.request.session['from'], self.request.session['to'])
        context = {}

        if 'players' in request.GET:
            request.session['last_players'] = request.GET.getlist('players')
        if 'count' in request.GET:
            request.session['last_count'] = request.GET.get('count')

        initial_count = int(request.session['last_count']) \
            if 'last_count' in request.session \
            and request.session['last_count'] \
            else 2
        initial_players = request.session['last_players'] \
            if 'last_players' in request.session \
            and request.session['last_players'] \
            else ''

        form = MatchmakerForm(request, initial={
            'count': initial_count,
            'players': initial_players,
        })

        if 'players' and 'count' in request.GET:
            players = [Player.objects.get(pk=x, owner=request.user)
                       for x in request.GET.getlist('players')]
            context['constellations'] = ConstellationFactory(
                players, int(request.GET.get('count'))
            ).get_constellations()
            if len(request.GET.getlist('players')) \
                    < int(request.GET.get('count')):
                form.errors['error'] = 'Choose more players !'
        context["matchmaker_form"] = form
        return render(
            request,
            template_name="matchmaker/matchmaker_form.html",
            context=context,
        )

templates/balancer/matchmaker_form.html
{% extends 'base.html' %}
{% block title %}Balancer{% endblock %}
{% block description %}This core element of Table Soccer Matchmaker calculates the teams to have the most balanced matches possible.{% endblock %}
{% block keywords %}balance, teams, equal, strength, ai{% endblock %}

{% block tipps %}
	<div class="alert alert-success" role="alert">
		You can choose more players than really playing.
	</div>
	<hr />
{% endblock %}
{% block head %}
{% load elements %}
<script>
	$(document).ready(function() {
		loadDataTables(1, 'asc');
	});
</script>
<style>
th{width:1%;}
#matchmaker #id_players li{
	float:left;
	margin-right: 5px;
}
</style>
{% endblock %} 


{% block content %}
{% load join_by_attr %}
<div id="matchmaker" class="container bg ">
	<form method="get">
		{% if matchmaker_form.fields.players.choices|length >= 2%}
			{% if matchmaker_form.errors %}
				<div class="alert alert-danger" role="alert">
					{{ matchmaker_form.errors.error }}
				</div>
			{% endif %}
		{% else %}
			<div class="alert alert-danger" role="alert">
				A Match needs at least 2 teams/player-teams. <a href="{% url 'player-new' %}" class="btn btn-warning">Create them first</a>
			</div>
		{% endif %}
		<table class="table table-striped table-bordered table-hover">
			<tr>
				<th>Players:</th>
			</tr>
			<tr>
				<td>{{ matchmaker_form.players }}</td>
			</tr>
			<tr>
				<th>Constellation:</th>
			</tr>
			<tr>
				<td>{{ matchmaker_form.count }}</td>
			</tr>
			
		</table>
		<input class="btn btn-primary btn-block" type="submit" value="Calculate Teams" />
	</form>
</div>

{% if constellations %}
<div class="table-responsive">
<table class="datatable table table-striped table-bordered table-hover">
<thead>
	<tr>
		<th class="w-25" scope="col">{% if constellations.0.team1.players|length == 1%}Single-Player-Team{% else %}Team (and <span class="badge badge-light">Players</span>){% endif %}</th>
		<th scope="w-25">Balance</th>
		<th class="w-25" scope="col">{% if constellations.0.team2.players|length == 1%}Single-Player-Team{% else %}Team (and <span class="badge badge-light">Players</span>){% endif %}</th>
		<th style="width:180px;" scope="col">Play</th>
	</tr>
</thead>

{% for constellation in constellations %}
<tr>
<!-- Team 1 -->
<td data-order="{{ constellation.team1.team.team_rating_as_int }}">
	<strong>
	{% if constellation.team1.team.name != None %}
		{% team_details_badge constellation.team1.team linkclass='primary' %}
	{% else %}
		<span href="#" tabindex="0" class="btn btn-warning" data-placement="bottom" data-toggle="popover" data-trigger="click" data-title="Create Team" data-container="body" type="button" data-html="true">
			<div class="popover-content d-none">
				<form method="post" action="{%url 'team-new'%}">{% csrf_token %}
					Teamname (optional): {{new_team_form.teamname}}
					{% for player in constellation.team1.players %}
						<input type="hidden" name="players" value="{{ player.pk }}">
					{% endfor %}
					<input type="hidden" name="next" value="{{ request.get_raw_uri }}">
				<button class="btn btn-primary btn-block mt-3" type="submit">Create Team</button>
				</form>
			</div>
			Create Team ({{ constellation.team1.strength }})</span>
	{% endif %}
	</strong>
	{% if not constellation.team1.team.is_player_team or not constellation.team1.team.name %}
		{% for player in constellation.team1.players %}
			{% player_details_badge player %}
		{% endfor %}
	{% endif %}
</td>
<!-- /Team 1 -->

<!-- Balance -->
<td data-order="{{ constellation.difference }}">
	<div class="progress" tabindex="0" data-trigger="focus" data-toggle="popover" data-placement="top" data-html="true" data-title="Teams comparison">
		<div class="popover-content d-none">
			<div class="container-fluid">
			<div class="row">
				<table class="table table-sm text-center">
					<tr><th colspan=3>Played games:</tr>
					<tr><td>{{ constellation.team1.team.get_win_draw_lose_sum }}</td><td>:</td><td>{{ constellation.team2.team.get_win_draw_lose_sum }}</td><tr>
					<tr><th colspan=3>Goal Factor:</tr>
					<tr><td>{% if constellation.team1.team.has_game %}{{ constellation.team1.team.goal_factor }}{% endif %}</td><td>:</td><td>{% if constellation.team2.team.has_game %}{{ constellation.team2.team.goal_factor }}{% endif %}</td><tr>
				</table>
			</div>
			</div>
		</div>
		<div class="progress-bar bg-primary" role="progressbar" style="width: {{ constellation.chance.0 }}%" aria-valuenow="{{ constellation.chance.0 }}" aria-valuemin="0" aria-valuemax="100">
			<strong>{{ constellation.chance.0 }}%</strong>
		</div>
		<div class="progress-bar bg-secondary" role="progressbar" style="width: {{ constellation.chance.1 }}%" aria-valuenow="{{ constellation.chance.1 }}" aria-valuemin="0" aria-valuemax="100">
			<strong>{{ constellation.chance.1 }}%</strong>
		</div>
	</div>
	{% if constellation.previous_matches %}
	<div class="container-fluid" >
		<div class="row">
			{% for match in constellation.previous_matches %}
				{% match_details_badge match match.firstteam t2show=False %}
			{% endfor %}
		</div>
	</div>
	{% endif %}
</td>
<!-- /Balance -->

<!-- Team 2 -->
<td data-order="{{ constellation.team1.team.team_rating_as_int }}"><strong>
	{% if constellation.team2.team.name != None %}
		{% team_details_badge constellation.team2.team linkclass='secondary' %}
	{% else %}
		<span href="#" tabindex="0" class="btn btn-warning" data-placement="bottom" data-toggle="popover" data-trigger="click" data-title="Create Team" data-container="body" type="button" data-html="true">
			<div class="popover-content d-none">
				<form method="post" action="{%url 'team-new'%}">{% csrf_token %}
					Teamname (optional): {{teamcreate_form.teamname}}
					{% for player in constellation.team2.players %}
						<input type="hidden" name="players" value="{{ player.pk }}">
						<input type="hidden" name="next" value="{{ request.get_raw_uri }}">
					{% endfor %}
				<button class="btn btn-primary btn-block mt-3" type="submit">Create Team</button>
				</form>
			</div>
			Create Team ({{ constellation.team2.strength }})</span>
	{% endif %}

	{% if not constellation.team2.team.is_player_team or not constellation.team2.team.name %}
	{% for player in constellation.team2.players %}
		{% player_details_badge player %}
	{% endfor %}
	</ul>
	{% endif %}
</td>
<!-- /Team 2 -->

<!-- Play -->
<td>
		<div class="container">
			<div class="row">
				{% if constellation.team1.team.name != None and constellation.team2.team.name != None %}
					<a href="{% url 'match-new' %}?firstteam={{constellation.team1.team.id}}&secondteam={{constellation.team2.team.id}}" type="button" class="btn btn-success">Start</a>
				{% else %}
					<div class="alert alert-info p-2" role="alert">
						Create Teams first
					</div>
				{% endif %}
			</div>
		</div>
</td>
<!-- /Play -->
</tr>

{% empty %}
    <li>No constellations.</li>
{% endfor %}

</table>
</div>
{% endif %}
{% endblock %} 